# Generated by Django 5.2.4 on 2025-07-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
