# Generated by Django 5.2.4 on 2025-07-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_userprofile_custom_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
